version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes:
      - ../esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
  rabbitmq:
    image: rabbitmq:management
    expose:
      - "5672"
    ports:
     - "15672:15672"
#     - "5672:5672"
  web1:
    build: ../www_server
#    ports:
#     - "8000:8000"
    volumes:
      - ./../www_server:/code
    depends_on:
      - rabbitmq
      - elastic
      - async_resolver1
      - async_resolver2
  web2:
    build: ../www_server
#    ports:
#      - "8001:8000"
    volumes:
      - ./../www_server:/code
    depends_on:
      - rabbitmq
      - elastic
      - async_resolver1
      - async_resolver2
  async_resolver1:
    build: ../async_resolver
    volumes:
      - ./../async_resolver:/code
    depends_on:
      - rabbitmq
  async_resolver2:
    build: ../async_resolver
    volumes:
      - ./../async_resolver:/code
    depends_on:
      - rabbitmq
  varnish:
    build: ../varnish
    ports:
      - "8000:80"
    volumes:
      - ./../varnish/default.vcl:/etc/varnish/default.vcl
    depends_on:
      - web1
      - web2
