version: '3'
services:
  web:
    build: ../www_server
#    ports:
#     - "8000:8000"
    volumes:
      - ./../www_server:/code
  web2:
    build: ../www_server
#    ports:
#      - "8001:8000"
    volumes:
      - ./../www_server:/code
  varnish:
      build: ../varnish
      ports:
        - "8000:80"
      volumes:
        - ./../varnish/default.vcl:/etc/varnish/default.vcl
      depends_on:
        - web
        - web2